#!/bin/sh

echo --- pull changes
git pull

echo --- update submodules
git submodule init
git submodule sync
git submodule update
git submodule foreach git checkout master
git submodule foreach git pull -f origin
