// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "ExpressionEvolver.Client.Windows.ObservableObject.#OnPropertyChanged`1(System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "ExpressionEvolver.Client.Windows.ObservableObject.#SetAndNotify`1(!!0&,!!0,System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1014:MarkAssembliesWithClsCompliant")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId = "0#", Scope = "member", Target = "ExpressionEvolver.Client.Windows.ObservableObject.#SetAndNotify`1(!!0&,!!0,System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "ExpressionEvolver.Client.Windows.ObservableObject.#OnPropertyChanged`1(System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "BaseLine", Scope = "member", Target = "ExpressionEvolver.Client.Windows.MainWindowViewModel.#BaseLine")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Property", Scope = "member", Target = "ExpressionEvolver.Client.Windows.ObservableObject.#SetAndNotify`1(!!0&,!!0,System.Linq.Expressions.Expression`1<System.Func`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1824:MarkAssembliesWithNeutralResourcesLanguage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.Double.ToString(System.String)", Scope = "member", Target = "ExpressionEvolver.Client.Windows.MainWindowViewModel.#PrintPopulation(GeneticAlgorithm.Population`1<System.Linq.Expressions.Expression`1<System.Func`2<System.Double,System.Double>>>,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.Int32.ToString", Scope = "member", Target = "ExpressionEvolver.Client.Windows.MainWindowViewModel.#PrintPopulation(GeneticAlgorithm.Population`1<System.Linq.Expressions.Expression`1<System.Func`2<System.Double,System.Double>>>,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "ExpressionEvolver.Client.Windows.MainWindowViewModel.#GetPoints(System.Collections.ObjectModel.ReadOnlyCollection`1<ExpressionEvolver.ExpressionEvolverResult>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.Double.ToString(System.String)", Scope = "member", Target = "ExpressionEvolver.Client.Windows.MainWindowViewModel.#PrintPopulation(GeneticAlgorithm.Population`1<System.Linq.Expressions.Expression`1<System.Func`2<System.Double,System.Double>>>,System.Int32,System.Collections.ObjectModel.ReadOnlyCollection`1<ExpressionEvolver.ExpressionEvolverResult>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.Int32.ToString", Scope = "member", Target = "ExpressionEvolver.Client.Windows.MainWindowViewModel.#PrintPopulation(GeneticAlgorithm.Population`1<System.Linq.Expressions.Expression`1<System.Func`2<System.Double,System.Double>>>,System.Int32,System.Collections.ObjectModel.ReadOnlyCollection`1<ExpressionEvolver.ExpressionEvolverResult>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "ExpressionEvolver.Client.Windows.MainWindowViewModel.#GetBestPoints(System.Collections.ObjectModel.ReadOnlyCollection`1<ExpressionEvolver.ExpressionEvolverResult>,System.Func`2<System.Double,System.Double>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Scope = "type", Target = "ExpressionEvolver.Client.Windows.MainWindowViewModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.Double.ToString(System.String)", Scope = "member", Target = "ExpressionEvolver.Client.Windows.MainWindowViewModel.#Evolve()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "value", Scope = "member", Target = "ExpressionEvolver.Client.Windows.MainWindowViewModel.#GetBestPoints(System.Collections.ObjectModel.ReadOnlyCollection`1<ExpressionEvolver.ExpressionEvolverResult>,System.Func`2<System.Double,System.Double>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "valueResult", Scope = "member", Target = "ExpressionEvolver.Client.Windows.MainWindowViewModel.#GetBestPoints(System.Collections.ObjectModel.ReadOnlyCollection`1<ExpressionEvolver.ExpressionEvolverResult>,System.Func`2<System.Double,System.Double>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "resultValue", Scope = "member", Target = "ExpressionEvolver.Client.Windows.MainWindowViewModel.#GetBestPoints(System.Collections.ObjectModel.ReadOnlyCollection`1<ExpressionEvolver.ExpressionEvolverResult>,System.Func`2<System.Double,System.Double>)")]
